# Generated by Django 4.1.7 on 2023-04-01 11:16

import Info_Data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id1', models.BigIntegerField()),
                ('User_id2', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Certified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Abstract', models.TextField()),
                ('Getting_Started', models.TextField()),
                ('Completed_Status', models.BooleanField()),
                ('Deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('E_mail', models.CharField(max_length=50)),
                ('GitHub_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('Programme', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=4)),
                ('Miscellaneous', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.tags')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_Theme', models.CharField(max_length=50, validators=[Info_Data.models.validate_Color_Theme])),
                ('Project_Visibility', models.CharField(max_length=50, validators=[Info_Data.models.validate_Project_Visibility])),
                ('Profile_Visibility', models.CharField(max_length=50, validators=[Info_Data.models.validate_Profile_Visibility])),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.project')),
                ('Tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user')),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Content', models.TextField()),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.project')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appeal', models.CharField(max_length=500)),
                ('Applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user')),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user'),
        ),
        migrations.CreateModel(
            name='Member_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user')),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.project')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.BigIntegerField()),
                ('Time', models.DateTimeField()),
                ('content', models.TextField()),
                ('Parent_id', models.BigIntegerField(blank=True, null=True)),
                ('Chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.chat_rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Group_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50)),
                ('Group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.group')),
                ('Mmeber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info_Data.user')),
            ],
        ),
    ]
